### ISSUE TITLE
Social media links are not opening in new page

### ISSUE THREAD

**Issue by suvasis-patra** [tyaga001/devtoolsacademy#20]
**Description**
When we click on the social media icons in the footer section, they are not opening on a new page.

**Expected Behavior**
When we click on any social media icon in the footer section, it should open on a new page. This improves the user experience.

**Do you want to work on this issue?**
Yes

**If "yes" to the above, please explain how you would technically implement this**
I will add target="_blank" to the  SocialLinks functional component in the Footer component of the Components **folder.**

**Comment by tyaga001** [comment]
@suvasis-patra pls go ahead and raise a PR if you want to work on this.

**Comment by suvasis-patra** [comment]
Sure, I have just raised a PR
